# Generated by Django 6.0.7 on 2026-07-31 13:57

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('python_course', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Company',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=100, unique=True)),
                ('slug', models.SlugField(blank=True, max_length=120, unique=True)),
                ('logo', models.ImageField(blank=True, null=True, upload_to='companies/logos/')),
                ('website', models.URLField(blank=True)),
                ('description', models.TextField(blank=True)),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': 'Company',
                'verbose_name_plural': 'Companies',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Tag',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=50, unique=True)),
                ('slug', models.SlugField(blank=True, max_length=60, unique=True)),
            ],
            options={
                'verbose_name': 'Tag',
                'verbose_name_plural': 'Tags',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='InterviewQuestion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('title', models.CharField(max_length=255)),
                ('slug', models.SlugField(max_length=255, unique=True)),
                ('problem_statement', models.TextField()),
                ('input_format', models.TextField(blank=True)),
                ('output_format', models.TextField(blank=True)),
                ('constraints', models.TextField(blank=True)),
                ('difficulty', models.CharField(choices=[('easy', 'Easy'), ('medium', 'Medium'), ('hard', 'Hard')], max_length=10)),
                ('editorial', models.TextField(blank=True, help_text='Detailed explanation of the approach.')),
                ('is_active', models.BooleanField(default=True)),
                ('companies', models.ManyToManyField(related_name='interview_questions', to='problems.company')),
                ('topic', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(class)ss', to='python_course.topic')),
                ('tags', models.ManyToManyField(blank=True, related_name='interview_questions', to='problems.tag')),
            ],
            options={
                'verbose_name': 'Interview Question',
                'verbose_name_plural': 'Interview Questions',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='InterviewHint',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('content', models.TextField()),
                ('order', models.PositiveIntegerField(default=1, help_text='Display order of this hint (lower numbers shown first).')),
                ('question', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='hints', to='problems.interviewquestion')),
            ],
            options={
                'verbose_name': 'Interview Hint',
                'verbose_name_plural': 'Interview Hints',
                'ordering': ['order'],
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='PracticeQuestion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('title', models.CharField(max_length=255)),
                ('slug', models.SlugField(max_length=255, unique=True)),
                ('problem_statement', models.TextField()),
                ('input_format', models.TextField(blank=True)),
                ('output_format', models.TextField(blank=True)),
                ('constraints', models.TextField(blank=True)),
                ('difficulty', models.CharField(choices=[('easy', 'Easy'), ('medium', 'Medium'), ('hard', 'Hard')], max_length=10)),
                ('editorial', models.TextField(blank=True, help_text='Detailed explanation of the approach.')),
                ('is_active', models.BooleanField(default=True)),
                ('topic', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(class)ss', to='python_course.topic')),
                ('tags', models.ManyToManyField(blank=True, related_name='practice_questions', to='problems.tag')),
            ],
            options={
                'verbose_name': 'Practice Question',
                'verbose_name_plural': 'Practice Questions',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='PracticeHint',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('content', models.TextField()),
                ('order', models.PositiveIntegerField(default=1, help_text='Display order of this hint (lower numbers shown first).')),
                ('question', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='hints', to='problems.practicequestion')),
            ],
            options={
                'verbose_name': 'Practice Hint',
                'verbose_name_plural': 'Practice Hints',
                'ordering': ['order'],
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='InterviewExample',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('input_data', models.TextField()),
                ('output_data', models.TextField()),
                ('explanation', models.TextField(blank=True)),
                ('order', models.PositiveIntegerField(default=1, help_text='Display order of this example on the question page.')),
                ('question', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='examples', to='problems.interviewquestion')),
            ],
            options={
                'verbose_name': 'Interview Example',
                'verbose_name_plural': 'Interview Examples',
                'ordering': ['order'],
                'abstract': False,
                'constraints': [models.UniqueConstraint(fields=('question', 'order'), name='unique_interview_example_order')],
            },
        ),
        migrations.CreateModel(
            name='InterviewSolution',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('language', models.CharField(choices=[('python', 'Python'), ('java', 'Java'), ('cpp', 'C++'), ('javascript', 'JavaScript')], max_length=20)),
                ('code', models.TextField()),
                ('explanation', models.TextField(blank=True, help_text="Optional notes specific to this language's implementation.")),
                ('question', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='solutions', to='problems.interviewquestion')),
            ],
            options={
                'verbose_name': 'Interview Solution',
                'verbose_name_plural': 'Interview Solutions',
                'abstract': False,
                'constraints': [models.UniqueConstraint(fields=('question', 'language'), name='unique_interview_solution_per_language')],
            },
        ),
        migrations.CreateModel(
            name='InterviewTestCase',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('input_data', models.TextField()),
                ('expected_output', models.TextField()),
                ('is_hidden', models.BooleanField(default=True, help_text='Hidden test cases are used for grading but not shown to the user.')),
                ('order', models.PositiveIntegerField(default=1, help_text='Execution/display order of this test case.')),
                ('question', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='test_cases', to='problems.interviewquestion')),
            ],
            options={
                'verbose_name': 'Interview Test Case',
                'verbose_name_plural': 'Interview Test Cases',
                'ordering': ['order'],
                'abstract': False,
                'constraints': [models.UniqueConstraint(fields=('question', 'order'), name='unique_interview_test_case_order')],
            },
        ),
        migrations.CreateModel(
            name='PracticeExample',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('input_data', models.TextField()),
                ('output_data', models.TextField()),
                ('explanation', models.TextField(blank=True)),
                ('order', models.PositiveIntegerField(default=1, help_text='Display order of this example on the question page.')),
                ('question', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='examples', to='problems.practicequestion')),
            ],
            options={
                'verbose_name': 'Practice Example',
                'verbose_name_plural': 'Practice Examples',
                'ordering': ['order'],
                'abstract': False,
                'constraints': [models.UniqueConstraint(fields=('question', 'order'), name='unique_practice_example_order')],
            },
        ),
        migrations.CreateModel(
            name='PracticeSolution',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('language', models.CharField(choices=[('python', 'Python'), ('java', 'Java'), ('cpp', 'C++'), ('javascript', 'JavaScript')], max_length=20)),
                ('code', models.TextField()),
                ('explanation', models.TextField(blank=True, help_text="Optional notes specific to this language's implementation.")),
                ('question', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='solutions', to='problems.practicequestion')),
            ],
            options={
                'verbose_name': 'Practice Solution',
                'verbose_name_plural': 'Practice Solutions',
                'abstract': False,
                'constraints': [models.UniqueConstraint(fields=('question', 'language'), name='unique_practice_solution_per_language')],
            },
        ),
        migrations.CreateModel(
            name='PracticeTestCase',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('input_data', models.TextField()),
                ('expected_output', models.TextField()),
                ('is_hidden', models.BooleanField(default=True, help_text='Hidden test cases are used for grading but not shown to the user.')),
                ('order', models.PositiveIntegerField(default=1, help_text='Execution/display order of this test case.')),
                ('question', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='test_cases', to='problems.practicequestion')),
            ],
            options={
                'verbose_name': 'Practice Test Case',
                'verbose_name_plural': 'Practice Test Cases',
                'ordering': ['order'],
                'abstract': False,
                'constraints': [models.UniqueConstraint(fields=('question', 'order'), name='unique_practice_test_case_order')],
            },
        ),
    ]
