FROM python:3.11-slim

RUN apt-get update && apt-get install -y \
    gcc \
    && rm -rf /var/lib/apt/lists/*

WORKDIR /app

RUN pip install --no-cache-dir celery redis

COPY . .

CMD ["celery", "-A", "workers.celery_tasks.celery", "worker", "-l", "info"]
